server:
  error:
    include-message: always
    include-binding-errors: always
  port: 9000
spring:
  datasource:
    driverClassName: 'com.mysql.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: 9fs7sn
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true